/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fastfoodgui;
import fastfoodcore.*;
import java.util.Collection;

/**
 *
 * @author rexle_000
 */
public class FastFoodGUI extends javax.swing.JFrame {
    
    private FastFoodCoord fastFood;

    /** Creates new form FastFoodGUI */
    public FastFoodGUI() {
        initComponents();
        fastFood = new FastFoodCoord();
        Collection<Meal> meals = fastFood.getMeals();
       addMeal.setListData(meals);
       
       Collection<Drink> drinks = fastFood.getDrinks();
       addDrink.setListData(drinks);
        
    }
    
    
    private void displayMeals()
   {
      
      Collection<Meal>meals = fastFood.getMeals();
      addMeal.setListData(meals);
      addMeal.setSelectedIndex(0);      
      
   }
    
   private void displayDrinks()
   {
      
      Collection<Drink>drinks = fastFood.getDrinks();
      addDrink.setListData(drinks);
      addDrink.setSelectedIndex(0);      
      
   } 
    
    
    
    
    
    
    
    
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        orderScreen = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderMeal = new m256gui.M256JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        orderDrink = new m256gui.M256JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        ordersTextArea = new javax.swing.JTextArea();
        orderButton = new javax.swing.JButton();
        addMenuScreen = new javax.swing.JPanel();
        meals = new javax.swing.JScrollPane();
        addMeal = new m256gui.M256JList();
        drinks = new javax.swing.JScrollPane();
        addDrink = new m256gui.M256JList();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        enterMealTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        enterPriceOfMealTextField = new javax.swing.JTextField();
        addMealButton = new javax.swing.JButton();
        deleteMealButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        enterDrinkTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addDrinkButton = new javax.swing.JButton();
        enterPriceOfDrinkTextField = new javax.swing.JTextField();
        deleteDrinkButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        viewOrders = new m256gui.M256JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1275, 950));

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select a meal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        orderMeal.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        orderMeal.setSelectionMode(0);
        orderMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        orderMeal.setPreferredSize(new java.awt.Dimension(100, 850));
        orderMeal.setSize(new java.awt.Dimension(100, 800));
        orderMeal.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                orderMealValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(orderMeal);

        jScrollPane2.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select a drink", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jScrollPane2.setPreferredSize(new java.awt.Dimension(200, 1000));

        orderDrink.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        orderDrink.setSelectionMode(0);
        orderDrink.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        orderDrink.setPreferredSize(new java.awt.Dimension(100, 850));
        orderDrink.setSize(new java.awt.Dimension(200, 1000));
        orderDrink.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                orderDrinkValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(orderDrink);

        ordersTextArea.setColumns(20);
        ordersTextArea.setRows(5);
        jScrollPane3.setViewportView(ordersTextArea);

        orderButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        orderButton.setText("ORDER");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout orderScreenLayout = new javax.swing.GroupLayout(orderScreen);
        orderScreen.setLayout(orderScreenLayout);
        orderScreenLayout.setHorizontalGroup(
            orderScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(orderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        orderScreenLayout.setVerticalGroup(
            orderScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderScreenLayout.createSequentialGroup()
                .addGroup(orderScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderScreenLayout.createSequentialGroup()
                        .addComponent(orderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1124, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        jTabbedPane1.addTab("ORDER", orderScreen);

        meals.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "Meals", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        addMeal.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        addMeal.setSelectionMode(0);
        addMeal.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                addMealValueChanged(evt);
            }
        });
        meals.setViewportView(addMeal);

        drinks.setViewportBorder(javax.swing.BorderFactory.createTitledBorder(null, "Drinks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        addDrink.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        addDrink.setSelectionMode(0);
        addDrink.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                addDrinkValueChanged(evt);
            }
        });
        drinks.setViewportView(addDrink);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Enter a meal");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Enter price for meal");

        addMealButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addMealButton.setText("Add meal");
        addMealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMealButtonActionPerformed(evt);
            }
        });

        deleteMealButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteMealButton.setText("Delete meal");
        deleteMealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMealButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(enterPriceOfMealTextField)
            .addComponent(addMealButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(enterMealTextField)
            .addComponent(deleteMealButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterMealTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterPriceOfMealTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(addMealButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(deleteMealButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Enter price for drink");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Enter a drink");

        addDrinkButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addDrinkButton.setText("Add drink");
        addDrinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDrinkButtonActionPerformed(evt);
            }
        });

        deleteDrinkButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deleteDrinkButton.setText("Delete drink");
        deleteDrinkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteDrinkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(enterDrinkTextField)
            .addComponent(enterPriceOfDrinkTextField)
            .addComponent(addDrinkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
            .addComponent(deleteDrinkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterDrinkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enterPriceOfDrinkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(addDrinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(deleteDrinkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addMenuScreenLayout = new javax.swing.GroupLayout(addMenuScreen);
        addMenuScreen.setLayout(addMenuScreenLayout);
        addMenuScreenLayout.setHorizontalGroup(
            addMenuScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMenuScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addMenuScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(meals)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(addMenuScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drinks, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        addMenuScreenLayout.setVerticalGroup(
            addMenuScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMenuScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addMenuScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(meals)
                    .addComponent(drinks, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addMenuScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("ADD MENU", addMenuScreen);

        viewOrders.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        viewOrders.setSelectionMode(0);
        viewOrders.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewOrders.setPreferredSize(new java.awt.Dimension(100, 850));
        viewOrders.setSize(new java.awt.Dimension(100, 800));
        jScrollPane4.setViewportView(viewOrders);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 587, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(616, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("VIEW ORDERS", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addDrinkValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_addDrinkValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_addDrinkValueChanged

    private void addMealValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_addMealValueChanged
        
    }//GEN-LAST:event_addMealValueChanged

    private void orderDrinkValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_orderDrinkValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_orderDrinkValueChanged

    private void orderMealValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_orderMealValueChanged
        
    }//GEN-LAST:event_orderMealValueChanged

    private void addMealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMealButtonActionPerformed
String theName = enterMealTextField.getText();
        int thePrice = Integer.parseInt(enterPriceOfMealTextField.getText());
        fastFood.addMeal(theName, thePrice);
        Collection<Meal> meals = fastFood.getMeals();
        addMeal.setListData(meals);
        orderMeal.setListData(meals);
        enterMealTextField.setText(" ");
        enterPriceOfMealTextField.setText(" ");       
        
        
        
       
    }//GEN-LAST:event_addMealButtonActionPerformed

    private void addDrinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDrinkButtonActionPerformed
        String theName = enterDrinkTextField.getText();
        int thePrice = Integer.parseInt(enterPriceOfDrinkTextField.getText());
        fastFood.addDrink(theName, thePrice);
        Collection<Drink> drinks = fastFood.getDrinks();
        addDrink.setListData(drinks);
        orderDrink.setListData(drinks);
        enterDrinkTextField.setText(" ");
        enterPriceOfDrinkTextField.setText(" "); 
    }//GEN-LAST:event_addDrinkButtonActionPerformed

    private void deleteMealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMealButtonActionPerformed
          Collection<Meal> meals = fastFood.getMeals();
        Meal theMeal = (Meal)addMeal.getSelectedValue();
        meals.remove(theMeal);
        addMeal.setListData(meals);
        orderMeal.setListData(meals);
    }//GEN-LAST:event_deleteMealButtonActionPerformed

    private void deleteDrinkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteDrinkButtonActionPerformed
        Collection<Drink> drinks = fastFood.getDrinks();
        Drink theDrink = (Drink)addDrink.getSelectedValue();
        drinks.remove(theDrink);
        addDrink.setListData(drinks);
        orderDrink.setListData(drinks);
    }//GEN-LAST:event_deleteDrinkButtonActionPerformed

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
     
                    

               Drink aDrink = (Drink)orderDrink.getSelectedValue();
       
        Meal aMeal = (Meal)orderMeal.getSelectedValue();        
        
        ordersTextArea.setText(aMeal.getName() +"\n"+ aDrink.getName());
                
       
        viewOrders.setListData(fastFood.getOrderNumber());
       
        StringBuilder sb = new StringBuilder();
        sb.append(aMeal);
        sb.append(aDrink);
       
             
                               
         
                
          
    }//GEN-LAST:event_orderButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastFoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastFoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastFoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastFoodGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastFoodGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private m256gui.M256JList addDrink;
    private javax.swing.JButton addDrinkButton;
    private m256gui.M256JList addMeal;
    private javax.swing.JButton addMealButton;
    private javax.swing.JPanel addMenuScreen;
    private javax.swing.JButton deleteDrinkButton;
    private javax.swing.JButton deleteMealButton;
    private javax.swing.JScrollPane drinks;
    private javax.swing.JTextField enterDrinkTextField;
    private javax.swing.JTextField enterMealTextField;
    private javax.swing.JTextField enterPriceOfDrinkTextField;
    private javax.swing.JTextField enterPriceOfMealTextField;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JScrollPane meals;
    private javax.swing.JButton orderButton;
    private m256gui.M256JList orderDrink;
    private m256gui.M256JList orderMeal;
    private javax.swing.JPanel orderScreen;
    private javax.swing.JTextArea ordersTextArea;
    private m256gui.M256JList viewOrders;
    // End of variables declaration//GEN-END:variables

}
